#spring:
#  datasource:
#    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
#      username: ${DEV_DB_USERNAME}
#      password: ${DEV_DB_PASSWORD}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EmployeeAssetManagement_DB
    username: postgres
    password: admin


